### ISSUE TITLE
How to get Micro ROS Agent docker working in serial mode?

### ISSUE THREAD

**Issue by Kelly-Coffey** [micro-ROS/docker#45]
When using the micro-ROS-Agent docker, the serial mode exits early compared to other modes.
udp and psuedo-serial appear to be working, but I have not tested with a client.

Below are the various commands I have tried.

ubu@ubu-VirtualBox:~$ sudo docker run -it microros/micro-ros-agent udp 8888
UDP agent initialization... OK
Enter 'q' for exit
q
ubu@ubu-VirtualBox:~$ sudo docker run -it microros/micro-ros-agent pseudo-serial
Pseudo-Serial initialization... Device: /dev/pts/1
OK
Enter 'q' for exit
q
ubu@ubu-VirtualBox:~$ ls /dev/serial/by-id
usb-FTDI_FT232R_USB_UART_AI02RNQC-if00-port0
ubu@ubu-VirtualBox:~$ sudo docker run -it microros/micro-ros-agent serial usb-FTDI_FT232R_USB_UART_AI02RNQC-if00-port0
Serial agent initialization... ubu@ubu-VirtualBox:~$ 
ubu@ubu-VirtualBox:~$ 
ubu@ubu-VirtualBox:~$ sudo docker run -it microros/micro-ros-agent serial --dev /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AI02RNQC-if00-port0
Error: Invalid arguments.
Usage: program <command>
List of commands:
    serial <device_name>
    pseudo-serial
    udp <local_port> [<discovery_port>]
    tcp <local_port> [<discovery_port>
ubu@ubu-VirtualBox:~$
ubu@ubu-VirtualBox:~$ sudo docker run -it microros/micro-ros-agent serial /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AI02RNQC-if00-port0
Serial agent initialization... ubu@ubu-VirtualBox:~$

**Comment by julibert** [comment]
Hi @Kelly-Coffey, did you try to expose the device to the container with the [--device](https://docs.docker.com/engine/reference/commandline/run/) option?
I think you could try something like:
```
sudo docker run -it --device /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AI02RNQC-if00-port0 serial --dev /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AI02RNQC-if00-port0
```
I hope it help you.

**Comment by Kelly-Coffey** [comment]
Hello, Thanks for the suggestion. 
Since I was able to install and build Micro ROS agent in a ros:dashing docker I was able to make some progress on this issue. I also got some suggestions from Brandon Cannaday's blog https://www.losant.com/blog/how-to-access-serial-devices-in-docker

What resolved this issue is the following:
Setup: On VirtualBox running Ubuntu Virtual Machine with Micro-ROS Dockers
1. First verify FTDI FT232 Serial device is seen by the Host machine.
2. In VirtualBox Menus "Devices>USB>USB Devices" enable "FTDI FT232R USB UART"
3. In the Ubuntu virtual machine find the serial device name with ls /dev/serial/by-id/*

example:
ubu@ubu-VirtualBox:~$ ls /dev/serial/by-id/*
/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AI02RNQC-if00-port0

Since the USB serial port can be plug and unplugged mount the /dev folder and  run the docker in Privileged mode with the following:

4. sudo docker run -it -v /dev:/dev --privileged microros/micro-ros-agent serial /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AI02RNQC-if00-port0 

5. You should see
Serial agent initialization... OK
Enter 'q' for exit
