### ISSUE TITLE
Docker image age?

### ISSUE THREAD

**Issue by gavanderhoorn** [micro-ROS/docker#77]
This is not *really* an issue, but Discussions has not been enabled.

Looking at [docker/microros/micro-ros-agent/tags](https://hub.docker.com/r/microros/micro-ros-agent/tags), all images, except `galactic` have seen their last push several months ago. `latest` and `rolling` are almost a year old.

We can of course build them locally, but would it be an option to push a recent build to Docker Hub?

**Comment by pablogs9** [comment]
Hello @gavanderhoorn, they used to be automatically built but some time ago Dockerhub removed this feature for free users. We will update them today.

**Comment by gavanderhoorn** [comment]
Perhaps something like what was implemented in https://github.com/osrf/docker_images/pull/598 could help here as well?

**Comment by pablogs9** [comment]
Solved in dd278e88dafe63a8e7f39437063e58ccf0649cb9

**Comment by gavanderhoorn** [comment]
nice, thanks

**Comment by gavanderhoorn** [comment]
related: what's the status of the `rolling` and `latest` images?

**Comment by pablogs9** [comment]
I guess that `latest` is not relevant and maybe we can deprecate it.

Regarding `rolling` there are some building problems, we will schedule some slots for checking and fixing it, probably after Humble release.

**Comment by gavanderhoorn** [comment]
Hi @pablogs9: has the automation stopped working again?

`microros/micro-ros-agent:galactic` and `rolling` are about a month old.

Specifically, they're missing https://github.com/eProsima/Micro-XRCE-DDS-Agent/pull/310, which fixes a blocking issue (for me, but I guess also for other users).

Could you perhaps take a look / kick a manual build?

Thanks

**Comment by pablogs9** [comment]
@gavanderhoorn done here: https://github.com/micro-ROS/docker/actions/runs/2343473340

**Comment by gavanderhoorn** [comment]
Thanks :+1: 

I noticed that job requires a manual start.

Would it not be more convenient -- for you -- to automate the builds? Or would you want to keep an eye on when they get updated?

Perhaps the `latest` image could be setup to track `HEAD`, with the warning it may break?
